config/routes.rb
Twitter::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tweets, only: [:new, :create, :destroy]
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/help', 		to: 'static_pages#help'
  get '/about', 	to: 'static_pages#about'
  get '/contact', 	to: 'static_pages#contact'


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
<h1>About us</h1><hr>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1><hr>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>How are you, Twitter?</h1>

  <h2>Mine today's tweets to measure how people around the country feel right now.</h2>

  <%= form_tag tweets_path, :method => :get, :class => "form-search text-center" do %>
  <div class="input-append">
<!--     <h4 class="heading">Search tweets now:</h4>
 -->    <%= text_field_tag :q, params[:q], :class => "search-query" %>
    <%= button_tag "Go!", :type => "submit", :class => "btn btn-medium" %>
  </div>
  <% end %>
  <div class="row-fluid">
    <div class="span4 well">
      <p class="lead">Step 1: Input search term<br><br><br></p>
    </div>

    <div class="span4 well">
    <p class="lead">Step 2: Get a visualization of the most recent tweets with that word, and how people feel</p>
    </div>

    <div class="span4 well">
    <p class="lead">Step 3: Take your data and visualization to go.<br><br></p>
    </div>
  </div>

</div>