config/routes.rb
Twitter::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tweets, only: [:new, :create, :destroy]
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/help', 		to: 'static_pages#help'
  get '/about', 	to: 'static_pages#about'
  get '/contact', 	to: 'static_pages#contact'


end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="span4"><h5><%= link_to   "About",     about_path %></h5>
    </div>
    <div class="span4"><h5><%= link_to "Contact", contact_path %></h5>
      <a href="http://twitter.com/machikoyasuda/">Twitter</a><br>
      <a href="http://github.com/machikoyasuda/">GitHub</a>
    </div>
    <div class="span4"><p>Made in Los Angeles.</p></div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class = "navbar-inner">
      <div class = "container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Twitter Sentiment Visualizer", root_path, id: "logo" %>

        <nav class="nav-collapse collapse">
          <ul class ="nav pull-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path   %></li>

            <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Register", new_user_path %></li>

          <% end %>
        </ul>
    
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
  <!-- Part I: Wrap all page content -->
    <div id="wrap">
      <!-- Fixed navbar -->
      <%= render 'layouts/header' %>
      <!-- Content -->
      <div class="container">
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
      <div id="push"></div>
    </div>
  <!-- Part II: Footer -->
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>